name: todowithprovider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  animated_text_kit: ^4.3.0
  flutter:
    sdk: flutter
  lottie: ^3.3.2
  provider: ^6.1.5+1
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/splashScreen/
